version: "3.7"

services:
  curso_ignite:
    image: postgres
    container_name: curso_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=curso_ignite
    volumes:
      - pgdata:/data/postgres
    network_mode: "host"
  app:
    build: .
    container_name: academia
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    network_mode: "host"



volumes:
  pgdata:
    driver: local