version: "3.9"

services:
  curso_ignite:
    image: postgres
    container_name: curso_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=curso_ignite
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - .:/usr/app
    links:
      - curso_ignite
    depends_on:
      - curso_ignite


volumes:
  pgdata:
    driver: local