version: "3.9"

services:
  db_ignite:
    image: postgres
    container_name: db_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_ignite
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rentx
    restart: always
  ports:
    - 3333:3333
    - 9229:9229
  volumes:
    - .:/user/app
  links:
    - db_ignite
  depends_on:
    - db_ignite

volumes:
  pgdata:
    driver: local